### ISSUE TITLE
Add Support for False Friends

### ISSUE THREAD

**Issue by cattaneod** [valentjn/vscode-ltex#11]
First, thank you very much for your work!

Would it be possible to add support for false friends, after setting the mother tongue?

**Comment by valentjn** [comment]
@catta202000 Thank you! And thanks for your suggestion. I didn't know about the false friends feature of LanguageTool.

LT<sub>E</sub>X 4.7.1 supports this with the new `ltex.additionalRules.motherTongue` setting. If you supply it without specifying a language model (*n*-gram data via `ltex.additionalRules.languageModel`), then a workaround uses the old false friend detection from LanguageTool's `false-friends.xml`.

For example, when checking English with German mother tongue, the wrong `My handy is broken.` (handy is a German pseudo-anglicism for mobile phone) will be warned about with and without a language model, but the correct `This will come in handy.` will be erroneously warned about only without a language model.

**Comment by cattaneod** [comment]
That was super fast!
Thank you so much for your work.
