### ISSUE TITLE
"Could not download/extract/run Java. You might want to try offline installation."

### ISSUE THREAD

**Issue by hhchi13** [valentjn/vscode-ltex#116]
Hi,

I tried to install LTEX in VScode on Windows 10. And I got an error "Could not download/extract/run Java. You might want to try offline installation.".

The "download and extract" part is OK. So it seems that "run Java" is the problem. I also tried offline installation but the error remained...

Any advice?

Thanks 

![image](https://user-images.githubusercontent.com/50938783/92317766-7434a800-efd2-11ea-87cf-1c0e3a12d89e.png)

**Comment by valentjn** [comment]
https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#how-to-report-bugs

The problem description above doesn't really contain any info. I need at least the output from the `LTeX Language Client` and `LTeX Language Server` panels.
