### ISSUE TITLE
Enable / Disable Specific Style Rules

### ISSUE THREAD

**Issue by MatthiasCarnein** [valentjn/vscode-ltex#13]
First, thank you so much for your work on this great tool!

Is it possible to enable or disable specific style rules? At the moment I am writing a document in British English (LTex 4.7.0, English language pack, language "en-GB").

This will issue a grammar error for sentences like: 
> I like optimisation.

with message:

> In British English, for some nouns, both ~s and ~z spellings are possible. By default, the rule for Oxford spelling is on for nouns and thus suggests 'optimization'.

Since I am not using Oxford spelling, I would like to disable this rule. Is there any way to do this in LTex?

In the commandline version of LanguageTools ([http://wiki.languagetool.org/command-line-options](http://wiki.languagetool.org/command-line-options)) you can use the `--disable` option:

`java -jar languagetool-commandline.jar --language "en-GB" --disable "OXFORD_SPELLING_NOUNS" file.txt`

Similarly, non-default rules can be enabled with the `--enable` option. You can also set the option in the GUI-version of LanguageTools which will create the key `disabledRules.en-GB=OXFORD_SPELLING_NOUNS` in the `~/.languagetool.cfg` config file.

Unfortunately, I have not found a way to set such an option in LTex. If it is currently not supported, maybe it could be added in the future with an additional option in `settings.json` such as: 

```
"ltex.disabledRules.en-GB": [
	"OXFORD_SPELLING_NOUNS"
]

```

**Comment by valentjn** [comment]
@MatthiasCarnein Thank you for the detailed feature request. This should be fixed with the new `ltex.<LANGUAGE>.disabledRules` and `ltex.<LANGUAGE>.enabledRules` settings in LT<sub>E</sub>X 4.7.4 (note that the language comes first in the names of the settings). Be sure to update the language extensions to 4.7.4 as well, as changes to language-specific setting schemes require new versions of the language extensions.

**Comment by MatthiasCarnein** [comment]
Wow, that was fast! Thank you so much, the new settings work perfectly.
