### ISSUE TITLE
Disable checking in specific blocks

### ISSUE THREAD

**Issue by tretum** [valentjn/vscode-ltex#14]
**Is your feature request related to a problem? Please describe.**
I have a lot of lstlisting blocks for a custom DSL that cause a lot of false suggestions due to the fact that it does not contain sentence structures and uses quotation marks for strings, etc.

**Describe the solution you'd like**
I would like to be able to disable the checking only for specific `\begin{XXX} ... \end{XXX}` blocks.
In my case i would like to disable checking for `\begin{lstlisting}[options] ... \end{lstlising}` blocks.

**Comment by valentjn** [comment]
@tretum Thanks for the feature request. This should be fixed with LT<sub>E</sub>X 4.7.5. There is now a built-in list for ignored environments and `lstlisting` is already part of it. Use the new `ltex.environments.ignore` setting if you want to ignore other environments as well.

**Comment by tretum** [comment]
Thank you very much for the quick implementation and thanks for keeping the project alive 🙂
