### ISSUE TITLE
Switch language based on babel package option in preamble

### ISSUE THREAD

**Issue by efaulhaber** [valentjn/vscode-ltex#140]
The basic way to choose a LaTeX document language is to provide the language as an option when loading the babel package (`\usepackage[LANGUAGE]{babel}`).

In the options I set `ltex.language` to `de-DE` since most of my documents are written in German. I don't know if I misconfigured something, but for me English LaTeX documents (that have `\usepackage[english]{babel}` in the preamble) are still checked in German unless I explicitly put a `\selectlanguage{english}` somewhere.

I would like the package to automatically check the document in the language that I provided as package option to babel.

**Comment by valentjn** [comment]
This is already addressed here: https://github.com/valentjn/vscode-ltex/issues/125#issuecomment-698415638

In short, the main problem is when preamble and text are in different files.

**Comment by efaulhaber** [comment]
Good point! I would suggest still adding the feature for short files without external preamble but adding information to the docs that the language must be explicitly provided for files that don't contain a preamble.

**Comment by valentjn** [comment]
That is a good suggestion, thanks. It's implemented now.

**Comment by valentjn** [comment]
Fix released in 8.0.0.
