### ISSUE TITLE
Add option to permanently show LTeX status in status bar

### ISSUE THREAD

**Issue by efaulhaber** [valentjn/vscode-ltex#141]
I would like to have an option to permanently show the status of the extension in the status bar.

I've made the experience with another spell checker, that an occasional look down to the status bar can prevent me from making unnoticed mistakes while the checker is not running for some reason.

**Comment by valentjn** [comment]
Could you be more specific? What is the status of LT<sub>E</sub>X for you?

The number of errors is displayed by VS Code, and something like "checking" or "not checking" would cause much visual noise as it would switch back and forth on every edit/keystroke. LT<sub>E</sub>X already displays "checking" for checks that take longer (> 5s).

**Comment by efaulhaber** [comment]
I usually get a lot of LTeX suggestions as I don't add every unknown name or word to a dictionary. That's why I changed the severity to "hint" to keep my "Problems" panel clean and I can see LaTeX warnings or overfull boxes immediately.
Therefore, I can't see if LTeX is currently active, if there are no errors in the part of code that I'm currently seeing.

So for me the "status" could simply be a "LTeX currently active" at the position where the "checking" status appears for longer checks.

**Comment by valentjn** [comment]
I see. Good suggestion. There will be an `ltex.statusBarItem` setting in the upcoming release.

**Comment by valentjn** [comment]
Fix released in 8.0.0.
