### ISSUE TITLE
Save user dictionary entries to a separate file instead of the settings.json

### ISSUE THREAD

**Issue by stakaz** [valentjn/vscode-ltex#144]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Using actual real-world examples that explain why you and many other users would benefit from the feature increases the request's chances of being implemented.

It is a minor problem: I would like to synchronize my user dictionaries across different programs. For this reason I have an extra dictionary file on my system (just newline separated words). With the current "add to user dictionary" I cannot write into this file but rather add the words into the settings.json file.

This has two negative effects:

1. I cannot syncronize with other programs and have to retype the new word in case I use it in another document in another editor
2. The list of adde words can become quite long and the settings file unpractically to read

**Describe the solution you'd like**

Save the user words (depending on the desired context) in

1. a workspace file (like it is done in the SpellRight extension), e.g., `.vscode/ltex-en_US.dict` or whatever
2. in a global file, e.g., `.config/code/ltex-en_US.dict`

**Describe alternatives you've considered**

The alternative in my case for the first point would be to watch changes in the settings file, than regex the part with the words and then append these words to my global dict file. This is however not a solution to the second point.

**Additional context**

Here was a related issue #118 which introduced the dictionary file for read but not for write. It could be just changing `:` to `!` or whatever to indicate the the words have to be saved into this file as well.

**Comment by stakaz** [comment]
Just in case, I also would generally suggest the same thing for the ignore sentences which are added if you click `Ignore in this sentence". It would be much better to have a separate file with these things than see then in the settings.json. For example as sometimes on want to version control the settings.json of a project to be able to update it on different machines. It would be much clearer to have these "often occuring changes" in a separate file.

**Comment by valentjn** [comment]
Could you open another issue for your comment about `Ignore in this sentence`? I think that's a different story (one issue per bug/feature makes it easier to keep track of things and to reference them, e.g., in the changelog).

**Comment by stakaz** [comment]
Yes of course.

**Comment by valentjn** [comment]
This is implemented now. I haven't tested it extensively, but it seems to work.

**Comment by valentjn** [comment]
Fix released in 8.0.0, see [external setting files](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#external-setting-files) in the docs.

**Comment by stakaz** [comment]
Thanks, that was a quick response. Great job!
