### ISSUE TITLE
Move the ignoreRuleInSentence automatically generated entries to a separate file

### ISSUE THREAD

**Issue by stakaz** [valentjn/vscode-ltex#145]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
Using actual real-world examples that explain why you and many other users would benefit from the feature increases the request's chances of being implemented.

It is not a problem but rather an inconvenience. The settings.json file is one which occasionally is edited by hand. However, the rules which I ignore in a file while editing by clicking the context button are a thing I will not type on my own and thus I would prefer to not see them in the settings.json file.

**Describe the solution you'd like**

generate a new file for Ltex and save the ignored rules there.

**Describe alternatives you've considered**

Keep as is and scroll.

**Additional context**

Moved from issue #144.

**Comment by valentjn** [comment]
Fix released in 8.0.0, see [external setting files](https://valentjn.github.io/vscode-ltex/docs/advanced-usage.html#external-setting-files) in the docs.
