### ISSUE TITLE
Limit RAM usage

### ISSUE THREAD

**Issue by pagdot** [valentjn/vscode-ltex#15]
**Is your feature request related to a problem? Please describe.**
The languagetool java process often uses >1GB of RAM

**Describe the solution you'd like**
Limit the ram usage with a setting

**Describe alternatives you've considered**
none

**Additional context**
https://github.com/languagetool-language-server/vscode-languagetool/issues/4

**Comment by valentjn** [comment]
@pagdot Thanks for the link to the old issue, which I wasn't aware of. In LT<sub>E</sub>X 4.7.6, there are now three new settings under `ltex.performance`. Even if not set, different values regarding Java heap size and LT cache size are used, which reduces memory usage by 30% (402 MB to 284 MB) in a quick test on my machine. I'm not sure if the new default values are not too small though. You wouldn't want to have `OutOfMemoryError`s...

Anyway, I think this fixes the issue for now. If tweaking the new settings does not help, feel free to reopen.
