### ISSUE TITLE
Check all documents command should use ltex.enabled setting

### ISSUE THREAD

**Issue by MarcelKoch** [valentjn/vscode-ltex#183]
**Is your feature request related to a problem? Please describe.**
In my current setup I've enabled ltex only for latex files, by editing `ltex.enabled`. After updating some ltex settings I usually run `check all documents`, but this also triggers the checks for some markdown files. This increases the overall runtime for the check, although I'm not interested in errors in my markdown files

**Describe the solution you'd like**
`check all documents` should only run on files matching the file types specified by `ltex.enabled`.

**Describe alternatives you've considered**
Check each file individually.

**Additional context**
The documentation explicitly says that `check all documents` runs on both markdown and latex files, but I don't think this is the expected behavior if `ltex.enabled` is customized.

**Comment by MarcelKoch** [comment]
It seem like I'm wrong and `check all documents` works as I expected. No errors from markdown files are reported when I set `ltex.enabled` accordingly.
I think I was confused by ltex's notification still listing more files to check than I have latex files. Maybe this could be adjusted? Otherwise I think the issue can be closed.

**Comment by valentjn** [comment]
Glad it worked out for you. You are right, LT<sub>E</sub>X did honor the `ltex.enabled` setting while checking, but not during the file search. This should be fixed now. Thanks for the input!

**Comment by valentjn** [comment]
Fix released in 8.2.0.
