### ISSUE TITLE
Quick jump to the next error

### ISSUE THREAD

**Issue by jiaqi61** [valentjn/vscode-ltex#186]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
 
I often do a complete spelling check of the whole document after I almost finish it. It would save me much time if ltex can automatically locate the next spelling error.

**Describe the solution you'd like**
Provide a shortcut which can jump to the next spelling error found by ltex, just like finding the next matching word when we searching a word.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by valentjn** [comment]
VS Code is responsible for navigation in the editor, not LT<sub>E</sub>X. In this case, use the command `Go to Next Error or Warning`, which is by default mapped to `F8`, see <https://code.visualstudio.com/docs/getstarted/keybindings>.

**Comment by jiaqi61** [comment]
> 
> 
> VS Code is responsible for navigation in the editor, not LTEX. In this case, use the command `Go to Next Error or Warning`, which is by default mapped to `F8`, see https://code.visualstudio.com/docs/getstarted/keybindings.

Thanks. I checked the URL you provide and it seems that `F8`  does not solve my problem. Nothing happens when I press `F8`.  The reason might be that the spelling error found by LTEX is not the  `Error or Warning` of VS Code.

**Comment by valentjn** [comment]
I did test it before I wrote my comment. See it in action here:

![vscode-ltex-186_1](https://user-images.githubusercontent.com/19839841/101658575-70874600-3a45-11eb-9ba7-c295ae0e2974.gif)

As you can see, the command is actually called `Go to Next Problem in Files (Error, Warning, Info)` (the page I linked seems to be outdated). You can also type the command's name directly into the Command Palette (`Ctrl+P`). However, using a keyboard shortcut is much faster.

There are many reasons why `F8` might not work for you:

- The default keyboard mapping has been changed - check as shown above if it says `F8` in the line of `Go to Next Problem in Files (Error, Warning, Info)` when opening the keyboard shortcuts (`Preferences: Open Keyboard Shortcuts` in the Command Palette).
- You changed the [`ltex.diagnosticSeverity`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexdiagnosticseverity) setting to `"hint"`. As the command name says, the `Go to Next Problem in Files (Error, Warning, Info)` command (and `F8`) only works with `"error"`, `"warning"`, and `"information"`.
- You're using a laptop keyboard, where you have to press an additional key (usually labeled `Fn`) to get the `F1-12` keys to work.

If you still have problems, open an issue over at [microsoft/vscode](https://github.com/microsoft/vscode), as this is an editor issue, not an LT<sub>E</sub>X issue.

**Comment by jiaqi61** [comment]
Typing the command in the Command Palette works for me, but `F8` still fails. I checked that `F8` is the right shortcut in VS Code, so the problem might be that `F8` is overridden by other programs, but I don't know which one it is yet. Fortunately, `Alt+F8` works for me. Thanks a lot.
