### ISSUE TITLE
How to spell check Rnw files (R Sweave)?

### ISSUE THREAD

**Issue by maikol-solis** [valentjn/vscode-ltex#22]
**Is your feature request related to a problem? Please describe.**
Is it possible spell check Rnw files in the same way that regular Latex files?

**Describe the solution you'd like**
Just the same spell checking workflow but in Rnw files.

**Comment by valentjn** [comment]
@maikol-solis Thanks for the suggestion! This will be in the upcoming LT<sub>E</sub>X release. To activate, change the language mode to `R Sweave`, which is provided by the LaTeX Workshop extension (see also https://github.com/James-Yu/LaTeX-Workshop/pull/1777).

**Comment by valentjn** [comment]
Fixed in 4.7.8.
