### ISSUE TITLE
Add possibility to add "wrong form" word to dictionary

### ISSUE THREAD

**Issue by BelKed** [valentjn/vscode-ltex#221]
**Is your feature request related to a problem? Please describe.**
As title says, I would like to add possibility to add "wrong form" word to dictionary.
When I write in Slovak language, there is no possibility like that. You could see that on this screenshot:
![picture](https://user-images.githubusercontent.com/66956532/104622540-b2815880-5691-11eb-9027-8527ae4b6927.png)
Also, there is screenshot of that problem in bottom section of Visual Studio Code:
![bottom section](https://user-images.githubusercontent.com/66956532/104623027-3b988f80-5692-11eb-9c19-e8db604bcb08.png)
Translation of text is following:
_Incorrect adjective shape (optických)
'optický'_

**Describe the solution you'd like**
I would like to add possibility to _Add 'word' to dictionary_ to dropdown menu like is there:
![kalorimetrickej](https://user-images.githubusercontent.com/66956532/104623779-fe80cd00-5692-11eb-816d-5d3cd1292fdb.png)

I hope, I wrote that issue understandable.
PS: Thanks for your super extension, it's really helpful for searching for almost invisible typos 😃

**Comment by valentjn** [comment]
Thanks for the feature request! I enabled the quick fix not only for the rule `MUZSKY_ROD_NEZIV_A`, but also for `ZENSKY_ROD_A` and `STREDNY_ROD_A`, as I think these rules are similar (just different genders). I don't know Slovak though.

I also removed the superfluous whitespace in the message of the rules, as the messages of most other languages are given in a single line without any indentation.

**Comment by BelKed** [comment]
Thanks for the fix.

> I enabled the quick fix not only for the rule MUZSKY_ROD_NEZIV_A, but also for ZENSKY_ROD_A and STREDNY_ROD_A, as I think these rules are similar (just different genders).

Yes, you are right, these are rules are similar. They are just different genders...

**Comment by valentjn** [comment]
Fix released in 8.3.0.

**Comment by BelKed** [comment]
Now I could add the "wrong" form of word to dictionary, but LTeX still underlines that word in document and shows the error...

**Comment by BelKed** [comment]
Thanks 😄

**Comment by valentjn** [comment]
Fix released in 8.4.0.

**Comment by BelKed** [comment]
Really thanks, now it works 😃
