### ISSUE TITLE
Beamer frame title is not spell checked

### ISSUE THREAD

**Issue by byjjustin** [valentjn/vscode-ltex#239]
Currently, all arguments after `\begin{env}` are ignored. However, in some cases they need to be spell checked. One such case is the slide title part in `\begin{frame}{Title}`. Maybe some new option can be added to `ltex.latex.environments` to allow users to customize this behavior.

**Comment by valentjn** [comment]
Thanks for the feature request! This should now be implemented.

**Comment by valentjn** [comment]
Feature released in 9.0.0.
