### ISSUE TITLE
Support for "ltex.latex.commands" where the argument is a separate sentence.

### ISSUE THREAD

**Issue by flindeberg** [valentjn/vscode-ltex#254]
**Is your feature request related to a problem? Please describe.**

I am writing a semi-technical larger text, an interdisciplinary PhD-thesis, in which I need to use a scattering amount of footnotes to make the text legible to readers from different disciplines.

Footnotes, i.e. `\footnote{}`, do not currently work with spell checking in a good way. Either you have to select `ignore` and completely ignore to spellcheck the contents of the footnote, or use `default` which incorporates it into the sentence structure. Neither is optimal.

**Describe the solution you'd like**

I'd like there to be an option to check the argument separately from the sentence the macro belongs to.

For example:
```
For \gls{routing}-related\footnote{That is issues pertaining to \gls{numbering} and unique identifiers, but completely separate from the \gls{dns}-system.} issues the following propositions hold:
```
would be nice to have checked as:
```
For dummy0-related issues the following propositions hold:

That is issues pertaining to dummy1 and unique identifiers, but completely separate from the dummy2-system.
```

Right now I get one "spelling request" with either "dummy" (also note the problem of the extra period):
```
For dummy0-related That is issues pertaining to dummy1 and unique identifiers, but completely separate from the dummy2-system. issues the following propositions hold:
```
or "ignore":
```
For dummy0-related issues the following propositions hold:
```
Neither are perfect, and come with their own issues.

**Describe alternatives you've considered**

I have tried workarounds, such as putting the content of the footnote in a macro to have it checked separately (and `ignore` set for footnote), but it is not really up to par with checking them separately.

**Comment by valentjn** [comment]
Footnote *are* already checked separately, as well as `\todo{...}` notes. So as a feature request, this would be a duplicate of #42.

For your example, I get zero diagnostics, as LT<sub>E</sub>X checks the following separately (see `LTeX Language Server` output):
- `That is issues pertaining to Dummy0 and unique identifiers, but completely separate from the Dummy1-system.`
- `For Dummy0-related issues the following propositions hold:`

If it's not working for you, then you probably added `\footnote{}` to `ltex.latex.commands`. This is a feature that was specifically requested before (see #63).* If you didn't add it to `ltex.latex.commands`, then this is a bug and I need some more info; it would then be best if you filled in the bug report template and replaced the description of this issue with it.

*) This means that `"default"` is not necessarily the same as not adding a command to `ltex.latex.commands`. The [docs](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexlatexcommands) say “The command is treated like **unknown** commands are treated by default: The command name itself is ignored, but the arguments are not ignored.” (emphasis mine), but `\footnote` is not a command unknown to LT<sub>E</sub>X, as it already does this magic processing.

**Comment by flindeberg** [comment]
You are right, I wonder how long I've had it in `ltex.latex.commands`. 

Ty for the quick reply!

**Comment by valentjn** [comment]
Duplicate of #42
