### ISSUE TITLE
ignore Bibtex files

### ISSUE THREAD

**Issue by astromancer** [valentjn/vscode-ltex#261]
**Is your feature request related to a problem? Please describe.**
Could be I missed this, but it would be lovely to have an option that allows you to turn off spell checking for all bib files.  

**Describe the solution you'd like**
A setting like: `ignoreBibtex: true` or `ignoredFiles: ["*.bib" , "*.sty"]`

**Describe alternatives you've considered**
As far as I understand this is only currently possible to disable spell checking for bib files by adding `% LTeX: enabled=false` to each and every bib file, or by setting
```json
"ltex.bibtex.fields": {
	"title": false,
	"journal": false,
	"eprint": false,
	// etc
}
```
for every possible bibtex keyword.  This feels like an unnecessary burden on the user.

**Additional context**
NA

Thanks!

**Comment by valentjn** [comment]
You should use [`ltex.enabled`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenabled) for this.

**Comment by astromancer** [comment]
Cool thanks i somehow missed that. you could provide a list here not just a boolean.

**Comment by valentjn** [comment]
Duplicate of #19
