### ISSUE TITLE
Use flexmark-ext-definition to correctly parse markdown definition list syntax

### ISSUE THREAD

**Issue by jnnkB** [valentjn/vscode-ltex#268]
**Is your feature request related to a problem? Please describe.**
When using vscode-ltex on a markdown file containing definition lists in the following format you get `LEERZEICHEN_VOR_AUSRUFEZEICHEN_ETC`errors with the message 'Vor Satzzeichen steht kein Leerzeichen (dahinter allerdings schon'. This translates to `SPACE_IN_FRONT_OF_EXCLEMATIONMARK_ETC` and 'You do not put punctation marks in front of spaces (but behind).'

```markdown
term
: The definition of *term*.
```

**Describe the solution you'd like**
I think the best way to solve this problem would be to use the [flexmark definition extension](https://github.com/vsch/flexmark-java/wiki/Extensions#definition-lists) or [here](https://github.com/vsch/flexmark-java/blob/master/flexmark-ext-definition/src/main/java/com/vladsch/flexmark/ext/definition/DefinitionItem.java). Then the document could be split accordingly into sentences.

**Describe alternatives you've considered**

I tried to add an ignore rule, but I didn't got it working. I could also ignore this rule – but this is only possible for the whole document.

It could also be possible to enable to user to ignore certain rules using regular expressions – but instead of only applying them to single sentences they would need to work on the whole document.

The activation of different flexmark plugins could also be done by the user.

**Additional context**
None

**Comment by valentjn** [comment]
Great suggestion, thanks.

**Comment by valentjn** [comment]
Fix released in 10.0.0.

**Comment by jnnkB** [comment]
Thanks a lot!
