### ISSUE TITLE
Problem with installation and initial configuration

### ISSUE THREAD

**Issue by michaelfsb** [valentjn/vscode-ltex#28]
I installed LTex but the spelling check is not running.

I configured the settings.json file with:
```
"ltex.enabled": true,    
"ltex.language": "pt-BR",
"ltex.trace.server": "verbose",
```

But I didn't find the log window: LTeX Language Server / LTeX Language Client output in View → Outpu.

![vs_code_print](https://user-images.githubusercontent.com/31492967/76716161-08057580-670e-11ea-816d-c58adac02454.png)

**Version information**
  VsCode 1.43
  LTex 4.7.10
  LTeX - Portuguese support 4.7.7
  Windows 10
  Java Version 8 Update 241

Can you help me please?

**Comment by valentjn** [comment]
@michaelfsb You additionally need the LaTeX Workshop extension from the Marketplace. Well, LT<sub>E</sub>X doesn't really "need" that extension, but the document type (the `Plain Text` in the bottom right corner of your screenshot) needs to be set to `LaTeX`, and VS Code by itself doesn't provide this document type, but LaTeX Workshop does. The solution is to install LaTeX Workshop, probably reload the window, and change the document type by clicking on `Plain Text` and selecting `LaTeX` (`*.tex` files are automatically opened with that type when you have LaTeX Workshop installed). Then wait a few seconds and LT<sub>E</sub>X should be loaded.

However, I understand that LT<sub>E</sub>X's readme could be clearer on this. Up to now, I somehow just assumed everybody who deals with L<sup>A</sup>T<sub>E</sub>X on VS Code has that extension. So I'm keeping this issue open until I have clarified the readme. Thanks for the input!

**Comment by michaelfsb** [comment]
Thanks for your answer.

A toolbox that recognizes the `.tex` file was really missing
I installed LaTeX Workshp and the spelling check is being performed correctly by LTeX.
