### ISSUE TITLE
OpenJDK Platform binary high CPU usage

### ISSUE THREAD

**Issue by Crautii** [valentjn/vscode-ltex#330]
After a Java update, every time i start Minecraft "OpenJDK Platform binary" uses 100% of my CPU. Before the update Minecraft did not even consume 10%. I do not know much about this things, can anyone please help me?

**Comment by valentjn** [comment]
This sounds like a Minecraft issue. [Minecraft bugs can be reported here.](https://www.minecraft.net/en-us/bugs) If you are sure this is a bug in LT<sub>E</sub>X, [please fill out the LT<sub>E</sub>X bug report template in a new issue](https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#how-to-report-bugs). Closing as invalid per contribution guidelines.
