### ISSUE TITLE
Non-breaking whitespaces in abbreviations (german)

### ISSUE THREAD

**Issue by Frosch** [valentjn/vscode-ltex#35]
**Is your feature request related to a problem? Please describe.**
In German, there is supposed to be a non-breaking **small** space (U+202F) in-between abbreviations. Languagetool does tell you to add a non-breaking whitespace between the parts, but it adds a full-width whitespace (U+202F) which looks completely weird. This probably happens because the small whitespace is not really supported in HTML iirc. So, Languagetool probably won't (/can't) change this behavior. However, in LaTeX it is completely fine and `\,` should be used for this.

So, it is really frustrating having numerous "errors" in your document just because you're using the correct kind of spacing :)

**Describe the solution you'd like**
It would be great if this rule could be catched for LaTeX to recognize `\,` for the spacing.

**Describe alternatives you've considered**
- Using the "wrong" spacing in your document: no errors, but looks weird and is incorrect for  German texts (as of DIN 5008)
- Disabling the rule: As this is an error I make kinda often, I'd love to keep this rule active :)

**Comment by valentjn** [comment]
@Frosch Thanks for the feature request. This is fixed now. For the record:

* The full-width whitespace is of course U+00A0.
* LT doesn't really depend on HTML, but works directly on plain Unicode strings. So another option would have been directly using the Unicode character in your L<sup>A</sup>T<sub>E</sub>X document, but then you'd need an engine like LuaT<sub>E</sub>X or X<sub>E</sub>T<sub>E</sub>X plus a font that contains that character ([it's possible to work around this](https://tex.stackexchange.com/a/150955)). Needless to say that using `\,` is the preferred solution.
* I think DIN 5008 only says to use a non-breaking space in abbreviations (I don't have a copy though), and I can't find anything about thin spaces in the Rechtschreibrat rules. So I think LT is actually working correctly. However, from a typographical POV, a thin non-breaking space looks much more appealing to me.

Edit: The Duden also recommends thin spaces (section _Textverarbeitung und E-Mails_, _Festabstände_). I'm just not sure if it's in the DIN as well.

**Comment by valentjn** [comment]
Fix released in 4.9.1.
