### ISSUE TITLE
Spelling mistake ?

### ISSUE THREAD

**Issue by bd1747** [valentjn/vscode-ltex#365]
Hi, 
I wonder if there might be an orthographic mistake in the setting doc:  https://github.com/valentjn/vscode-ltex/blob/dfd3a16f0f3c975d90f50c683fe55b51ae3ce4bd/package.nls.json#L195

Is the use of "will in" a mistake ? Do you mean "within a specific sentence" ? 

Thank you for this useful VSCode package !

**Comment by valentjn** [comment]
Yeah, of course. Well spotted.

**Comment by valentjn** [comment]
Fixed in 11.0.0.
