### ISSUE TITLE
SEMICOLON_COLON_SPACING in autoref to labels with smicolon

### ISSUE THREAD

**Issue by alanlivio** [valentjn/vscode-ltex#37]
Is your feature request related to a problem? Please describe.

The following code receives the SEMICOLON_COLON_SPACING error
\autoref{fig:architecture}

The same error not occur with:
\ref{fig:architecture}

**Comment by valentjn** [comment]
Fix released in 4.9.2.

**Comment by alanlivio** [comment]
Thanks. Good work.
