### ISSUE TITLE
Autocomplete words

### ISSUE THREAD

**Issue by TheKayneGame** [valentjn/vscode-ltex#409]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
While typing your document it's not uncommon to make mistakes. most of these are minor spelling mistakes. Wouldn't it be useful if LTeX had could use the same language server to request simple word completion. 

**Describe alternatives you've considered**
I have tried dictionary autocomplete (https://marketplace.visualstudio.com/items?itemName=yzhang.dictionary-completion)
and Google Autocomplete me (https://marketplace.visualstudio.com/items?itemName=jaydenlin.google-complete-me)
but they both work suboptimally

**Additional context**
auto complete could work like this (dictionary autocomplete)
but then using the LTeX language server
![image](https://user-images.githubusercontent.com/5954012/133090479-176d6244-f54e-4b6b-995c-062fcb12e0ad.png)

**Comment by valentjn** [comment]
Thanks for the suggestion. This is implemented now for English (`en-*`) and German (`de-*`). In other languages, dictionaries are either missing (e.g., French), very large (e.g., Breton), or don't have a delimiter between the entries (e.g., Italian). The downside is a 20MB increase in download size/disk space usage.

**Comment by valentjn** [comment]
Feature released in 12.2.0.
