### ISSUE TITLE
Setting invalid by default

### ISSUE THREAD

**Issue by PierreMarchand20** [valentjn/vscode-ltex#41]
**Describe the bug**
I just installed this extension and it seems that there is an issue with the settings:
<img width="482" alt="image" src="https://user-images.githubusercontent.com/15056323/82755581-cd3a5080-9dd4-11ea-99a6-6a0011edcadd.png">

But when I add them 
<img width="373" alt="image" src="https://user-images.githubusercontent.com/15056323/82755612-05da2a00-9dd5-11ea-9e68-e2354258a658.png">

it removes the warning.

**Steps to reproduce**

1. I just installed the extension and its French version and I did not touch anything.

**LTeX configuration**
Please attach any LTeX-related configuration settings from your `settings.json`.

** Log files**
First, set the `ltex.trace.server` setting in your `settings.json` to `"verbose"`. Then, reload the VS Code window and reproduce the bug. Go to `View` → `Output` and select `LTeX Language Server` and `LTeX Language Client` in the drop-down list. Paste or attach the relevant parts of these logs here in the GitHub issue.

**Version information**
List here the version information of the relevant software.

- Operating system: macOS xx.xx
- VS Code: 1.45.1
- LTeX: 4.9.3
- LTeX language extensions: French
- Java:
openjdk 11.0.2 2019-01-15
OpenJDK Runtime Environment 18.9 (build 11.0.2+9)
OpenJDK 64-Bit Server VM 18.9 (build 11.0.2+9, mixed mode)
**Additional context/information**
I actually tried to add the feature of this extension in Latex-Utility (but not maintained anymore), so I am quite happy to discover this extension!

**Comment by valentjn** [comment]
Thanks for the report. I noticed this a few days ago. It should be fixed on the 5.x branch.

**Comment by valentjn** [comment]
Fix released in 5.0.0.
