### ISSUE TITLE
Remove content of some commands from the natural flow (footnotes)

### ISSUE THREAD

**Issue by tobiasdiez** [valentjn/vscode-ltex#42]
**Is your feature request related to a problem? Please describe.**
Some commands don't add text at exactly this point, but display their arguments as footnotes or in the margin (e.g. `\footnote` or `\todo`). This is currently not supported by `ltex`. For example
```Test is a fibration\footnote{Fibration in the sense of Serre.}```
reports a "repeated word warning" for fibration.

**Describe the solution you'd like**
Remove these sentences from the normal text and check them separately.

**Describe alternatives you've considered**
Couldn't come up with good alternatives. One could convert `footnote` to a dummy text, but this also destroys the original sentence.

**Comment by tobiasdiez** [comment]
That was quick. Thanks a lot!

**Comment by valentjn** [comment]
@tobiasdiez No worries. Fix released in 5.0.0.
