### ISSUE TITLE
No checking of LaTeX in Neovim due to language ID mismatch

### ISSUE THREAD

**Issue by valentjn** [valentjn/vscode-ltex#425]
@valentjn ops, I just noticed that it's not working by default on LaTeX files in vim/neovim. Your changes seem to be missing this from my original fork:

```diff
@@ -61,12 +62,11 @@
     "onCommand:_ltex.openLatexExample",
     "onLanguage:bibtex",
     "onLanguage:html",
-    "onLanguage:latex",
+    "onLanguage:tex",
     "onLanguage:markdown",
     "onLanguage:org",
     "onLanguage:restructuredtext",
-    "onLanguage:rsweave",
-    "onNotebook:*"
+    "onLanguage:rsweave"
   ],
   "main": "./dist/extension",
   "contributes": {
@@ -149,7 +149,7 @@
           "default": [
             "bibtex",
             "html",
-            "latex",
+            "tex",
             "markdown",
             "org",
             "restructuredtext",
@@ -160,7 +160,7 @@
             true,
             false,
             [
-              "latex",
+              "tex",
               "markdown"
             ]
           ]
```

Vim/NeoVim usually doesn't have a "latex" filetype, it's named "tex".

Besides this, imo, coc.nvim support should be mentioned in vscode-ltex's README and as Vim/NeoVim client in the list of clients in ltex-ls's README. Otherwise it's hard to spot.

In case you wish but don't have a copy on my fork ready (as I dropped it already from online repo), I may put up the patch as a gist.

_Originally posted by @oblitum in https://github.com/valentjn/ltex-ls/issues/103#issuecomment-945003025_

**Comment by valentjn** [comment]
This is probably a bug in coc.nvim. The [LSP spec recommends](https://microsoft.github.io/language-server-protocol/specification#textDocumentItem) that clients use `latex` for L<sup>A</sup>T<sub>E</sub>X and `tex` for (plain) T<sub>E</sub>X files. coc-ltex is following the specs. I guess this is caused by neoclide/coc.nvim#757.

**Comment by oblitum** [comment]
I agree it's a coc.nvim issue, I'm currently [fixing it locally](https://codeberg.org/oblitum/dotfiles/commit/09d708800a235da98981ef1609e66803965c81be) with `g:coc_filetype_map` as suggested in the referred issue. Feel free to close this here.

**Comment by valentjn** [comment]
I opened an upstream PR here: neoclide/coc.nvim#3433

I guess it's going to take a while until it's merged and released (judging from the date of coc.nvim's last release in December 2020). So coc-ltex should include a workaround in the docs for the time being. That's why I'll keep this issue open as a documentation bug. I'm in the process of restructuring the whole documentation, and this will be added to a page about installing coc-ltex. As soon as that happens, this issue will be closed.

**Comment by oblitum** [comment]
@valentjn coc.nvim point releases take a long of time to happen, mostly no one bothers about them because of the `release` branch, we generally pick "releases" from there, it's a branch whose purpose is solely to have a pre compilation ready, every commit in it is a release. This is not usual, but it's how the project works.

Though, due to chemzqm temporary absence, even the release branch has not received an update lately. Hopefully it will come back on track.

**Comment by valentjn** [comment]
[The workaround is now documented.](https://valentjn.github.io/ltex/vscode-ltex/installation-usage-coc-ltex.html#how-to-install-and-use) Closing, see above.

@oblitum I see, thanks for the explanation. It's indeed unusual. I guess the way most people get the software is what counts as “release”. As that seems to be that `release` branch for coc.nvim (at least that's what it says in its installation instructions), it will suffice for the PR changes to be on the `release` branch.

However, due to the squashing strategy of the branch, we won't be able to specify a coc.nvim version that coc-ltex will require, and it's going to be hard to find out which `release` commits contain the PR without looking at/relying on the correctness of the squash commit messages.

**Comment by Drazulino** [comment]
and how that workaround would look on an init.lua?
