### ISSUE TITLE
Add to dictionary not available for de-CH

### ISSUE THREAD

**Issue by uvoglu** [valentjn/vscode-ltex#431]
**Describe the bug**
When applying a quick fix on a underlined work, there is no "Add ... to dictionary" option if a language like `de-CH` or `de-AT` is active for the document. It is, however, available for the same word if the language is set to `de-DE`, for example.

**Steps to reproduce**t

1. Set language to `de-CH` either globally or for the project via settings.json
2. Write an obviously wrong word, like "aefwe"
3. Wait for spell check to mark the word
4. Hover over the word and select "Quick fixes"
5. → There is no option to add to dictionary
6. Do the same thing, but this time with language set to `de-DE`
7. → Now, "Add 'aefwe' to dictionary" is available as an option in quick fixes.

**Expected behavior**
Add to dictionary should also be available to `de-CH` (and other languages where this feature does not work)

**LTeX configuration**
Please paste all configuration settings starting with `ltex.` from your `settings.json`. You can help us by temporarily removing some irrelevant settings from your `settings.json` and see if the bug still occurs.

<details>

```
{
    "ltex.language": "de-CH"
}
```

</details>

**Version information**
List here the version information of the relevant software.

- Operating system: macOS 11.6
- VS Code: 1.61.1
- vscode-ltex: 12.1.0

**Comment by valentjn** [comment]
Thanks for the report. We had that problem before, for French (valentjn/ltex-ls#47). Therefore, I just tried all LanguageTool languages manually. Austrian German and Swiss German were the only ones for which the quick fix didn't show up.

**Comment by valentjn** [comment]
Fix released in 12.2.0.

**Comment by uvoglu** [comment]
Really cool! 😎

Thanks a lot for the quick fix!
