### ISSUE TITLE
Disable LTex populating the autocomplete / intellisense list

### ISSUE THREAD

**Issue by noelfarrugia** [valentjn/vscode-ltex#443]
**Is your feature request related to a problem? Please describe.**
Whenever I am typing a LaTeX document, the `LTeX` extension suggests words from the dictionary. This is extremely annoying to have the completion window pop-up when typing. I tried looking for an option to disable this, but had no luck.

**Describe the solution you'd like**
Have a way of disabling the `LTeX` extension from populating the suggestions list.

**Describe alternatives you've considered**
Tried to increase the delay using the `editor.quickSuggestionsDelay` setting, but that made the snippets take longer to show up as well, which is far from ideal.

**Additional context**
Figure of the annoying suggestions that I cannot turn off
![image](https://user-images.githubusercontent.com/10677306/139228506-748f2498-2770-41fd-9ae5-bf603bee2322.png)

**Comment by valentjn** [comment]
You need to set `"editor.quickSuggestions": false`, or `"editor.quickSuggestions": {"other": false, [...]}`. Then, you can use `Ctrl+Space` to trigger the suggestions.

I didn't realize that VS Code has this on by default, because on all my machines, it's disabled. I'm not sure if there's a way of disabling this just for LT<sub>E</sub>X.

**Comment by noelfarrugia** [comment]
The problem with disabling `quickSuggestions` is that to trigger snippets you would need to press `Ctrl+Space` which is a bit annoying. I think disabling LTeX suggestions would be the better overall solution.

**Comment by valentjn** [comment]
Curiously, it doesn't happen in Markdown, only L<sup>A</sup>T<sub>E</sub>X and other languages.

I don't see a way to handle this properly. A proper solution would be telling VS Code somehow not to show suggestions from LT<sub>E</sub>X while typing, but to show them when pressing `Ctrl+Space`. There's also no way for the language server to find out why the completion request was triggered. Both completions while typing (the LSP calls it &ldquo;24x7 code complete&rdquo;) and `Ctrl+Space` have the same [`CompletionTriggerKind`](https://microsoft.github.io/language-server-protocol/specifications/specification-3-17/#completionTriggerKind) value of `Invoked`.

As LT<sub>E</sub>X should not have this irritating behavior with VS Code's default settings, the only option is to disable LT<sub>E</sub>X completion by default. There is now a setting `ltex.completionEnabled` to enable them again.

**Comment by noelfarrugia** [comment]
That's excellent! Thank you so much! Do you know when v13.0.0 will be released?

**Comment by valentjn** [comment]
I can't announce any date as they greatly depend on my availability and my spare time. But you can try it out in the [nightly pre-release](https://github.com/valentjn/vscode-ltex/releases), see the [docs for more info](https://valentjn.github.io/ltex/vscode-ltex/contributing.html#how-to-test-pre-releases).

**Comment by valentjn** [comment]
Fix released in 13.0.0.
