### ISSUE TITLE
Skip minted environments in LaTeX

### ISSUE THREAD

**Issue by EmeraldSnorlax** [valentjn/vscode-ltex#463]
Note: Per the contribution guidelines, deleting parts of the template or not filling in vital information may result in the issue to be immediately closed as invalid.

**Is your feature request related to a problem? Please describe.**
When pasting inline code into the document, (usually with the package `minted`), LTex gets very angry and causes a load of grammar / spelling errors to be flagged. It creates so much noise that finding actual errors becomes near impossible.

**Describe the solution you'd like**
Not checking for spelling inside codeblocks, allowing sections / scopes to be ignored by LTex, perhaps by editing the settings.

Or maybe a system similar to ESLint's `/* eslint-disable */`.

**Describe alternatives you've considered**
Not pasting inline code?

**Additional context**
![image](https://user-images.githubusercontent.com/43452521/142179862-485beb3d-ed92-4f19-977c-4318a75b2506.png)
this is very painful to mentally filter

**Comment by valentjn** [comment]
LT<sub>E</sub>X already skips code blocks by default, but only `lstlisting` and `verbatim` environments. `minted` environments should be easy to add to the default list.

In the meantime, you can do this manually by setting [`ltex.latex.environments`](https://valentjn.github.io/ltex/settings.html#ltexlatexenvironments) to `{"minted": "ignore"}`.

Also, LT<sub>E</sub>X already features support for [magic comments](https://valentjn.github.io/ltex/advanced-usage.html#magic-comments) to skip some parts of documents. Read the docs for more info.

**Comment by valentjn** [comment]
Fix released in 13.1.0.
