### ISSUE TITLE
Option to add multiple words to the dictionary at once

### ISSUE THREAD

**Issue by chirag127** [valentjn/vscode-ltex#473]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is that I'm always frustrated when my md file have many words which are shown as spelling error but are actual names of something.

**Describe the solution you'd like**
A clear and concise description of what I want to happen is that there should be a option to add all spelling error to the dictionary.

**Describe alternatives you've considered**
I can't think of any.

**Additional context**
This is the file. I have verified that all the spelling mistakes are not mistakes and I don't want press Add to dictinary 56 times and press ctrl + , 56 times and go to every other word 56 times.
[The Vijayanagar Empireppt.md](https://github.com/valentjn/vscode-ltex/files/7587185/The.Vijayanagar.Empireppt.md)

**Comment by valentjn** [comment]
[Please read the FAQ.](https://valentjn.github.io/ltex/faq.html#how-can-i-fix-multiple-spelling-errors-at-the-same-time)

**Comment by valentjn** [comment]
Duplicate of #23
