### ISSUE TITLE
Load languages on demand instead of having language extensions

### ISSUE THREAD

**Issue by valentjn** [valentjn/vscode-ltex#6]
All these language extensions pollute the Marketplace and are pretty confusing. It would be nice to have a prompt after installing LT<sub>E</sub>X allowing to download languages. We would still have to provide `*.vsix` files for offline installation.

**Comment by hirschsn** [comment]
You would also have to include some kind of update mechanism, wouldn't you?

**Comment by valentjn** [comment]
@hirschsn I guess this could be handled by updates of the main extension (e.g., download the latest version of the language extension that has smaller or equal version number compared to the version of the main extension). Besides, the language extensions only really have to be updated if LT is updated. We'd have to make sure that the LT versions of main extension and language extension match.

BTW, I got the idea from here: https://github.com/microsoft/vscode-cpptools/tree/master/Extension#offline-installation

**Comment by valentjn** [comment]
So the current status here is that I'm working on downloading all dependencies on-demand from within LT<sub>E</sub>X: language server, LanguageTool with all its languages, even Java if needed/desired (see #5). The initial version will only have the option to download all languages at once, not individually, since implementing that would require quite a bit of effort. However, as the main point of this issue was removing the need for the language extensions, this would solve this issue for me.

**Comment by valentjn** [comment]
The code for downloading ltex-ls on-demand is now in `master`. As mentioned above, this is a feasible fix from my POV.

**Comment by valentjn** [comment]
Fix released in 5.0.0.
