### ISSUE TITLE
clicking "Disable rule" creates a list not dictionary as expected

### ISSUE THREAD

**Issue by paddyroddy** [valentjn/vscode-ltex#61]
**Describe the bug**
When I right click and click `Disable rule` rather than manually editing `settings.json` it is not added correctly.

**Steps to reproduce**
Steps to reproduce the behaviour:

1. Go to document with rule breaking
2. Click on `Disable rule`
3. Scroll down to location in `settings.json`

**Expected behavior**
the JSON should be like `"ltex.disabledRules": {"en-GB": ["OXFORD_SPELLING_ISE_VERBS"]}` but instead is like `"ltex.disabledRules": ["OXFORD_SPELLING_ISE_VERBS"]`

**LTeX configuration**
`"ltex.language": "en-GB"`

**Version information**

- Operating system: macOS 10.15.5
- VS Code: 1.46.0
- vscode-ltex: 5.0.1

**Additional context/information**
If I'm manually editing settings.json then it disables rules as expected

**Comment by valentjn** [comment]
Thanks for the report. Fix released in 5.0.2.
