### ISSUE TITLE
unpaired symbol " with starting quotation ``

### ISSUE THREAD

**Issue by claudius-kienle** [valentjn/vscode-ltex#659]
**Describe the bug**
It is common to cite in latex with the opening qotation `` and closing quotation " to generate the correct quotation marks. The LTeX plugin highlights this as ```Unpaired symbol: '"' seems to be missingLTeX[EN_UNPAIRED_BRACKETS]```.

**Steps to reproduce**
Create a text like:
```latex
John said, ``the wether is nice today".
```

**Expected behavior**
Since this is the correct formatting for citation in latex, the warning should not appear.

**Version information**
- Operating system: Linux (5.10.123-1-MANJARO)
- VS Code: 1.67.2
- vscode-ltex: v13.1.0

**Comment by valentjn** [comment]
Closing quotes in L<sup>A</sup>T<sub>E</sub>X are `''` (i.e., two single apostrophes), not `"` (one double apostrophe).

**Comment by claudius-kienle** [comment]
Thank you for your response. I completely missed that.

**Comment by kylebutts** [comment]
Relatedly, a single quote formed as `text' produces a `EN_UNPAIRED_BRACKETS' error
