### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by kakosf** [valentjn/vscode-ltex#661]
- Issue Type: `Performance`
- Extension Name: `vscode-ltex`
- Extension Version: `13.1.0`
- OS Version: `Windows_NT x64 10.0.19044`
- VS Code version: `1.69.1`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///c%3A/Users/kakos/AppData/Local/Temp/valentjn.vscode-ltex-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-loa
[valentjn.vscode-ltex-unresponsive.cpuprofile.txt](https://github.com/valentjn/vscode-ltex/files/9101171/valentjn.vscode-ltex-unresponsive.cpuprofile.txt)

**Comment by valentjn** [comment]
Please follow [vscode-ltex's bug report guidelines](https://valentjn.github.io/ltex/vscode-ltex/contributing.html#how-to-report-bugs) and fill out vscode-tex's bug report issue template.
