### ISSUE TITLE
Magic comments to specify blocks of text that LTeX can ignore?

### ISSUE THREAD

**Issue by ayala-io** [valentjn/vscode-ltex#67]
**Is your feature request related to a problem? Please describe.**
Love LTeX, but for large documents with large sections of code-like/computer-generated listings, LTeX goes crazy and flags many spelling/grammar problems. For me, going through the problems list and clicking "Ignore" for every single one is time consuming, or somewhat slow (i.e. after choosing to ignore one specific problem LTeX detected, it took a few seconds to register before the problem is removed from the list... now try to repeat that for 200+ problems).

**Describe the solution you'd like**
I noticed LTeX supports Magic comments. How about a way to specify via Magic Comments like "LTeX Ignore Start" and "LTeX Ignore end" between blocks of text where we want LTeX to completely ignore spelling/grammar checking. This solution would be sufficient for me. Others might want additional options to ignore certain rules for a particular block of text.

**Describe alternatives you've considered**
Going through the problem list and clicking ignore one-by-one. It takes way too much time, I often just don't bother with it anymore but it would good to see a clean file.

**Additional context**
None.

**Comment by valentjn** [comment]
Fixed. Out of curiosity, why couldn't you use [`ltex.environments.ignore`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenvironmentsignore) (L<sup>A</sup>T<sub>E</sub>X) or [`ltex.markdown.ignore`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexmarkdownignore) (Markdown)? That would be the preferred way.

**Comment by ayala-io** [comment]
Thank you for your consideration.

Actually, I just didn't know about [`ltex.environments.ignore`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexenvironmentsignore). This is a good temporary solution but even then I still would like LTeX to check some text and ignore other text that use the same environment. Having a blanket ignore environment rule wouldn't work in this case. Also my suggestion would be helpful in ignoring text in the preamble (unless there's an environment associated with that too?)

**Comment by valentjn** [comment]
Ah, I see. It's definitely a good feature suggestion, thank you.

For most false positives in the preamble, [`ltex.commands.ignore`](https://valentjn.github.io/vscode-ltex/docs/settings.html#ltexcommandsignore) can be used. A lot of common preamble commands are already ignored by default, so if you come across a command that you think is widely used but not ignored by default, feel free to suggest adding it to the [default list](https://github.com/valentjn/ltex-ls/blob/646b43390f2bd6466303477cc8692af408998feb/ltexls-core/src/main/java/org/bsplines/ltexls/parsing/latex/DefaultLatexCommandSignatures.java).

**Comment by ayala-io** [comment]
Thank you again for all of your efforts and for working on this feature. Will take a look at `ltex.commands.ignore` for the preamble commands and will make suggestions accordingly.

**Comment by valentjn** [comment]
Fix released in 6.0.0.
