### ISSUE TITLE
Manual instalation instructions

### ISSUE THREAD

**Issue by pawelurbanski** [valentjn/vscode-ltex#69]
I followed the manual instalation instructions due to the package size. Unfortunately neither stable nor insider release of VS Code recognizes VSIX file as an extension package.

* Installing from the extensions panel worked,
* I get the prompt and both downloads for Java and LTEX complete,
* After opening a markdown file Java was not found,

What I did:

* Copied the extracted Java files and pointed to the folder using settings.json value,
* The path points to the top directory containing 'lib'' and 'bin' folders,
* I pointed to the directory containing LTEX Java jar files in teh same manner,

After restarting VS Code and opening a markdown file I keep getting the error about Java being not found. My system is 64-bit and I'm using the latest stable and insider editions of VS Code. 'ltex.enabled' key is set to: 'true'. The version of jars downloaded by the extension is: 6.0.1.

Any hints will be appriciated. If the output from the diagnostics would be useful just let me know and I'll get it.

**Comment by pawelurbanski** [comment]
After installing OpenJDK 11 and adding it to the system path everything is working properly. I guess that the following changes in the instructions would be desired:

* Point to open source precompiled installation packages of Open JDK,
* Inform about the fallback of letting the extension download and create a local environment.

**Comment by valentjn** [comment]
Glad it worked out for you. But did you read https://valentjn.github.io/vscode-ltex/docs/installation-how-to-use.html#offline-installation? I think everything is explained pretty extensively there. There's multiple links to AdoptOpenJDK, and it states that LT<sub>E</sub>X downloads Java and extracts it to the extension folder (if this is what you mean by "local environment").

**Comment by pawelurbanski** [comment]
Yes, I followed the instruction. The extension did download and extract the Open JDK zip, but it was not launching. Once I installed the Java JDK it started working.
