### ISSUE TITLE
Spellcheck directly from the main right click menu instead of using the lightbulb thingy

### ISSUE THREAD

**Issue by samuelstjean** [valentjn/vscode-ltex#83]
**Is your feature request related to a problem? Please describe.**
It would be useful (if possible, could be a limitation of vscode) to have the word suggestion directly fro the menu, instead of having to click quick fix and then looking at the suggestion. It would save about two clicks by mistakes. The idea is to have something similar to any good old spell checker such as found in modern web browser - a list that provides plausible replacement directly and the user just clicks on it.

**Describe the solution you'd like**
When a mistake is found, the list of possible spellings is given directly on the menu from a right click.

**Describe alternatives you've considered**
A submenu indicating possible fixes/replacement as to not clutter the main menu too much

**Additional context**
Kind of like this, but form within the extension to have a quick access to replacements

![screenshot](https://user-images.githubusercontent.com/3030760/88481913-27b67100-cf2c-11ea-9a58-2e428ca6ae9d.png)

If there is a lot of replacement it can become cluttered fast though, hence why a submenu with potential suggestions for word replacement might be useful.

**Comment by valentjn** [comment]
Thanks for the suggestion, but this is not straightforward: VS Code requests the quick fixes only when the user requests them, i.e., this would be when the context menu is opened, but VS Code has to wait for the language server (LT<sub>E</sub>X LS) to respond with the list of quick fixes.

I think this is more a question of how VS Code wants to present quick fixes coming from extensions. If every extension started to put their stuff into the context menu, it'd soon be pretty cluttered. One of the things I like about VS Code is it's clean UI, even with many extensions installed. I'm not sure why LT<sub>E</sub>X quick fixes should deserve special treatment over other extensions.

My suggestion would be, if you're unhappy with the presentation of quick fixes within VS Code, think about how you would do it instead and open an issue in the VS Code repo.

Apart from that, I'm not convinced yet why having the entries in the context menu would be significantly more convenient than the current solution:

* Context menu would be two clicks: Right-click to open the menu, and left-click on the suggested word.
* Current solution is two clicks: Hover over the word, left-click `Quick fix...` in the box that appears, and left-click on the suggested word. Or instead, if you're more of a keyboard person, navigate to the word, press `Ctrl+.`, and select the suggested word. No clicks, just a few keystrokes. This also works for replacing multiple words at once, just select a range of text before pressing `Ctrl+.`.

**Comment by samuelstjean** [comment]
Well the idea was just that's how it's done in sublime text (and most text editor and web browsers as far as I could tell), which is slightly faster because I guess that's how I expected it to be, I know it's so selfish though. Anyway,

1. Yes it is indeed cluttered when you have many things (in sublime I end up with huge ass menus because of other extensions now that I see it), so maybe they do not allow it just to prevent people abusing it.
2. I misread the quick link as ctrl + , the first time, no wonder it was 'broken' and not working, my fault on that one.

I figured it would maybe not be allowed by vscode (or at least disregard the point of having uncluttered menus), so I guess you may close this false feature request since it does not necessarily fall on this extension here as you mentioned. Thanks for the ctrl + . tip though, I was wondering why it was always opening my settings instead.

**Comment by valentjn** [comment]
No worries. Closing as this request should be resolved in [microsoft/vscode](https://github.com/microsoft/vscode).
