### ISSUE TITLE
Command in vscode to lint all workspace

### ISSUE THREAD

**Issue by universemaster** [valentjn/vscode-ltex#84]
**Is your feature request related to a problem? Please describe.**
In a workspace with many files, I often want to check all files against ltex, but this requires opening them one-by-one to even see if there are any results in vscode's _Problem_ view.

**Describe the solution you'd like**
A command in vscode to run ltex on the entire workspace, available in the Cmd-Shift-P command search box.  All problems should then appear in the _Problems_ view.

**Comment by valentjn** [comment]
Thanks for the feature request! This will be in the next feature release.

**Comment by valentjn** [comment]
Fix released in 6.2.0.
