### ISSUE TITLE
An vs a with mathematics

### ISSUE THREAD

**Issue by tobiasdiez** [valentjn/vscode-ltex#92]
**Is your feature request related to a problem? Please describe.**
When using mathematical expressions, the an-vs-a check leads to suboptimal results. For example, 
```
This is an $n$-dimensional problem.
```
results in a warning (although it is grammatically correct as $n$ is pronounced "an"). 

**Describe the solution you'd like**
No warning message in the above example, but a warning if "a" is used instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by valentjn** [comment]
This is a known issue, see first point of https://valentjn.github.io/vscode-ltex/docs/contributing-code-issues.html#known-issues-and-limitations. It's not possible to solve this without fully parsing L<sup>A</sup>T<sub>E</sub>X with proper macro expansion etc. Even then, it would still be hard to decide (e.g., whether a `u` is really like `uniform` or rather like `undecidable`; actually, even LanguageTool warns for the correct `This is a u-dimensional space.`)

This is exactly what LT<sub>E</sub>X's `Ignore in this sentence` feature was invented for.

**Comment by tobiasdiez** [comment]
I agree that is not possible to have a solution that works in all cases without a complete parsing of Latex. But it should be fairly straightforward to support the most common single-letter expressions like `$n$, $N$, \( n \)$`, which I guess already cover a lot of cases.

Maybe its possible to use the dummy feature and replace these expressions by some word having the same sound as the single-letter. For example, use "antic" in place of "n", so that LangugeTools sees `This is a antic-dimensional problem.`?

**Comment by valentjn** [comment]
Fair enough, I thought this was about solving this in general. Thanks for the request.

**Comment by tobiasdiez** [comment]
Thanks a lot for the quick implementation! Much appreciated.

**Comment by valentjn** [comment]
Fix released in 6.3.0.
